version: "3.9"

services:
  app:
    build: ./docker/php
    container_name: pos_app
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: pos_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pos_phpmyadmin
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - "${PMA_PORT}:80"

volumes:
  db_data:
